### PR TITLE
Add Windows x86 batch scripts for creating mega tiles

### PR DESCRIPTION
**Pull request by sergi4ua**
Port mewmew's batch scripts for creating megatiles for Tiled

### CODE REVIEW

**Review by mewmew — COMMENTED** [review]
LGTM. Just one question. Where is the download link for `montage.exe`? I tried to find it but failed so far :)

**Comment by ghost** [comment]
Up front in the readme: https://sergi4ua.github.io/cellar/montage.zip

**Comment by mewmew** [comment]
> Up front in the readme: https://sergi4ua.github.io/cellar/montage.zip

Thanks. I was just wondering where @sergi4ua got the exe from. Is it built from source or downloaded from the ImageMagick web page?

**Comment by ghost** [comment]
Looks like it is ImageMagick itself, or at least the backend:
```
Version: ImageMagick 7.0.10-6 Q16 x86 2020-04-06 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
```

**Comment by mewmew** [comment]
> Looks like it is ImageMagick itself, or at least the backend:
> 
> ```
> Version: ImageMagick 7.0.10-6 Q16 x86 2020-04-06 http://www.imagemagick.org
> Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
> ```

@galaxyhaxz are you a Wizard, how can you pull out such information from binary executables. I thought they were written in `1`s and `0`s?

**Comment by mewmew** [comment]
Hmm, I installed ImageMagick now from https://imagemagick.org/download/binaries/ImageMagick-7.0.10-7-Q16-x86-static.exe

However, once installed I can't find the `montage.exe` file.

From `C:/Program Files (x86)/ImageMagick-7.0.10-Q16`:

```
dcraw.exe
hp2xx.exe
imdisplay.exe
magick.exe
unins000.exe
```

**Comment by ghost** [comment]
One of them is probably the GUI and the other is CLI (just guessing).

> Are you a Wizard

<details>
<summary> clicky </summary> 

image
</details>

**Comment by ghost** [comment]
Ah ok, from google:
`When you install on Windows, there is a box you can tick if you want the legacy components like montage.exe. I guess you didn't tick it.`
(https://www.imagemagick.org/discourse-server///viewtopic.php?f=1&t=34854)

**Comment by mewmew** [comment]
> Ah ok, from google:
> `When you install on Windows, there is a box you can tick if you want the legacy components like montage.exe. I guess you didn't tick it.`
> (https://www.imagemagick.org/discourse-server///viewtopic.php?f=1&t=34854)

Yay! That worked.

Downloaded https://imagemagick.org/download/binaries/ImageMagick-7.0.10-7-Q16-x86-dll.exe and ticked the box you mentioned.

screenshot_2020-04-24_00:47:57

**Comment by mewmew** [comment]
The plot thickens. Now it seems "my" version of `montage.exe` is way smaller than the on in the PR.

From `ImageMagick-7.0.10-Q16` on my system:

```
du -hs montage.exe 
40K	montage.exe
```

From this PR:

```
du -hs ~/Downloads/montage.exe 
13M	/home/u/Downloads/montage.exe
```

**Edit:** so it looks like I have the `-7` version instead of the `-6` version.

```
Version: ImageMagick 7.0.10-7 Q16 x86 2020-04-20
```

Strange that this version is so much smaller.

Oh, on a second thought that's probably because I used the DLL version instead of the static version. Two sec.

**Comment by ghost** [comment]
That was my thought. You can also get version `6` here: https://imagemagick.org/download/windows/releases/

Most likely the static version links the DLLs for portability.

**Comment by mewmew** [comment]
Perfect! So, there was an a ZIP file for these in the *portable* version. The `-7` is at https://imagemagick.org/download/binaries/ImageMagick-7.0.10-7-portable-Q16-x86.zip

I got `-6` from http://ftp.icm.edu.pl/packages/ImageMagick/binaries/ImageMagick-7.0.10-6-portable-Q16-x86.zip which matches up perfectly with the one included in the PR.

Thanks @galaxyhaxz for the shared hunt and thanks @sergi4ua for the PR! :)

merging.

**Pull request merged**
